services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "1011:5000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "1010:5173"
    restart: unless-stopped
