services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:5173"
    restart: unless-stopped
