services:
  backend:
    build: ./src/backend
    env_file:
      - ./src/backend/.env
    ports:
      - "1011:5000"
    restart: unless-stopped
  frontend:
    build: ./src/frontend
    env_file:
      - ./src/frontend/.env
    ports:
      - "1010:5173"
    restart: unless-stopped
